
employment_status: all

companies:
  Octant: https://www.linkedin.com/company/octantbio/
  ProteinQure: https://www.linkedin.com/company/proteinqure/
  insitro: https://www.linkedin.com/company/insitro/
  'Deep Genomics': https://www.linkedin.com/company/deep-genomics/
  '1859': https://www.linkedin.com/company/1859ai/
  'Vevo Therapeutics': https://www.linkedin.com/company/vevo-therapeutics/
  'Arbor Biotechnologies': https://www.linkedin.com/company/arborbio/
  'e-therapeutics': https://www.linkedin.com/company/e-therapeutics-plc/
  Atomwise: https://www.linkedin.com/company/atomwise/
  'Vedanta Biosciences': https://www.linkedin.com/company/vedanta-biosciences-inc-/