
employment_status: all

companies:
  Octant: https://www.linkedin.com/company/octantbio/
  ProteinQure: https://www.linkedin.com/company/proteinqure/
  insitro: https://www.linkedin.com/company/insitro/
  'Deep Genomics': https://www.linkedin.com/company/deep-genomics/
